### ISSUE TITLE
Upgrade to Grails 3

### ISSUE THREAD

**Issue by alexanderfranke** [domurtag/runtime-datasources#2]
Hey,

I tried to bring the plugin to Grails 3 and local tests are successful. The changes can be found here: https://github.com/alexanderfranke/runtime-datasources. I'm quite new to grails so I'm not sure whether I missed something in the process. Should I create a pull request for that?

**Comment by alexanderfranke** [comment]
this is the commit: 
https://github.com/alexanderfranke/runtime-datasources/commit/9c4c7b617db8e4c15fe0be5f5504cd220faf9b28

**Comment by domurtag** [comment]
Hi Alexander,

Thanks for updating this to Grails 3. If you create a pull request I'll merge your changes. Before you create the pull request, could you also test publishing it to Bintray? Here's a [tutorial](https://medium.com/@benorama/how-to-publish-your-grails-3-plugin-to-bintray-c341b24f567d) that explains how to publish a Grails 3 plugin to Bintray. I'll replace your Bintray account settings with mine (in `build.gradle`) after I've merged the pull request.

**Comment by alexanderfranke** [comment]
Hey,
I did exactly this already as I needed it for an internal project: https://bintray.com/alexanderfranke/plugins/alexanderfranke.plugins%3Aruntime-datasources/view

**Comment by donalmurtagh** [comment]
Great, so just create a PR with your changes and I'll merge them and publish it.

**Comment by domurtag** [comment]
Great, so just create a PR with your changes and I'll merge them and publish it.

**Comment by domurtag** [comment]
By the way, I see you published it as version `0.2-grails3`. Is using `-grails3` in the version to indicate a plugin that is compatible with Grails 3 a convention that is widely adopted, or just something you decided yourself. It's a good idea, in my opinion.

**Comment by alexanderfranke** [comment]
That's just what I did and found appropriate, as only compatibility changed but not functionality.

**Comment by domurtag** [comment]
I've published it https://bintray.com/domurtag/plugins/domurtag.plugins%3Aruntime-datasources/view
